# Generated by Django 5.2.6 on 2025-09-09 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourism', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('visit', 'Visit Place'), ('meal', 'Meal'), ('transport', 'Transportation'), ('accommodation', 'Accommodation'), ('activity', 'Activity/Experience'), ('rest', 'Rest/Free Time')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_planner.dailyplan')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.place')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trip_type', models.CharField(choices=[('cultural', 'Cultural Heritage'), ('adventure', 'Adventure & Nature'), ('relaxation', 'Relaxation & Wellness'), ('family', 'Family Fun'), ('historical', 'Historical Sites'), ('culinary', 'Culinary Experience'), ('photography', 'Photography Tour'), ('business', 'Business Travel')], max_length=20)),
                ('budget_range', models.CharField(choices=[('low', 'Low Budget (< $50/day)'), ('medium', 'Medium Budget ($50-150/day)'), ('high', 'High Budget (> $150/day)')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('group_size', models.IntegerField(default=1)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='trip_planner.tripplan'),
        ),
        migrations.CreateModel(
            name='TripPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trip_type', models.CharField(choices=[('cultural', 'Cultural Heritage'), ('adventure', 'Adventure & Nature'), ('relaxation', 'Relaxation & Wellness'), ('family', 'Family Fun'), ('historical', 'Historical Sites'), ('culinary', 'Culinary Experience'), ('photography', 'Photography Tour'), ('business', 'Business Travel')], max_length=20)),
                ('duration_days', models.IntegerField()),
                ('template_data', models.JSONField(default=dict)),
                ('estimated_budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('popularity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.province')),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedTripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='trip_planner.tripplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'trip_plan')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('trip_plan', 'day_number')},
        ),
        migrations.CreateModel(
            name='TripPlanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='trip_planner.tripplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trip_plan', 'user')},
            },
        ),
    ]
