# Generated by Django 5.2.6 on 2025-09-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['hierarchy_level', 'price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='hierarchy_level',
            field=models.IntegerField(default=0),
        ),
    ]
