# Generated by Django 5.2.6 on 2025-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='spam_confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence score for spam detection (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='spam_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
